### ISSUE TITLE
feat: Add .config file to gitignore

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#11]
You may have noticed in the most recent PR that one of the changes was a change from Daniel's to Jiheon's .config file. We want everyone to be able to have their own .config file that doesn't get pushed to the repo. To do that, we want to put .config in the gitignore. Who would like to take on learning about this and doing it for us?
@npovejsil @voglerdaniel @Jihyeonbae @Mbye20

**Comment by atkissoncj** [comment]
We should also have a data folder in the gitignore and we can store the raw data, pre-processed data, then the final dataset. Those would just be updated by hand when there is a new change.

**Comment by voglerdaniel** [comment]
Closing - complete
