### ISSUE TITLE
feat: Add a feature on mapper to plot categorical variables

### ISSUE THREAD

**Issue by Mbye20** [uwescience/WaterReuseDSSG2024#116]

**Comment by atkissoncj** [comment]
This is not quite a full description of the issue as described to me by @Mbye20 yesterday. Categorical variables should be handled by default in the existing schema. What @chayek would like is the ability to choose that a continuous variable gets treated categorically, if I understood it correctly. This requires the ability to set an argument to treat a continuous variable as quantiles and then provide the quantiles of interest. *This might be something we could expect the user to provide and not provide it ourselves*. Thoughts?
