### ISSUE TITLE
feat: Create virtual environment

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#12]
We need to create an renv file so that we can all be using consistent versions of R and packages. Who wants to learn about an implement this?
@npovejsil @voglerdaniel @Mbye20 @Jihyeonbae

**Comment by npovejsil** [comment]
potentially still need I think - for r environment

**Comment by npovejsil** [comment]
require() in the .rmd creator script/tutorial instead
