### ISSUE TITLE
chore: break up and reshuffle drivers conceptual structure 

### ISSUE THREAD

**Issue by npovejsil** [uwescience/WaterReuseDSSG2024#14]
Add "economic development" as a driver 
Brainstorm other names/divisions for drivers

**Comment by miriamhacker** [comment]
See: Slide 3 in ["Source of Truth" document](https://docs.google.com/presentation/d/1mIQob57JuBIeedbJ7Kpx_MqS-U43rzPL6dUZXC04lq4/edit?usp=sharing)

**Comment by atkissoncj** [comment]
How are we going to be able to close this issue? What criteria will allow it to be marked as complete? Is it connected to a milestone?

**Comment by npovejsil** [comment]
I think this is updated and we can close it. Confirmation from PLs?

**Comment by atkissoncj** [comment]
I think so, yes. I include a static view of the current state of that dynamic process.

![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/57195396/d710e2e5-a700-4e20-815c-4d007dadc64d)
