### ISSUE TITLE
code: Select variables & create initial maps for selected variables 

### ISSUE THREAD

**Issue by npovejsil** [uwescience/WaterReuseDSSG2024#15]

**Comment by atkissoncj** [comment]
Connected to #19 #18 . Also connected to others?

**Comment by atkissoncj** [comment]
This is revised to making sure that we can process all the variables that Carolyn has selected for us.

**Comment by atkissoncj** [comment]
From Carolyn's Slack message:
Four variables in example formats that I would like to be able to easily map (think of this as user stories for a generalized mapping tool):
Flooding risk to roads (Column W) from [CVI Data Excerpts.xlsx](https://docs.google.com/spreadsheets/d/1YXLgsgYGoR-VPtyBVWU7coUfSs3nDmTA/edit?usp=drive_link&ouid=114492738005045724615&rtpof=true&sd=true) (values to be associated with a census shapefile based on an ID column). An extension example that I will need to do will be crossing the CWNS facility locations with the flood risk by census track to create flood risk values for each facility.  
[@Curtis Atkisson](https://uw-dssg-2024.slack.com/team/U074VQB1HL1)
 Let me know if that is a pre-processing step or something you can build in to the mapping functionality (point data that you want to assign attributes from a shapefile to and then map)
Any column from [WWpctr_5arc.nc](http://wwpctr_5arc.nc/) (raster with global coverage that needs to be cut to only include grid cells covering parts of the US)
SWIVULN from [SGD_Coastal_Vulnerabilities.csv](https://docs.google.com/spreadsheets/d/1iyinkUCtNlKfNNH6tVOQt42Db5xmUgQOREg9fz8FdZA/edit?usp=drive_link), using [Catchment_CONUS_coastline](https://drive.google.com/drive/folders/1ll9fXEcoh5sg_Bpvk_g04Hbyv2V0Jzk3?usp=drive_link) (values with an identifier tying it to a polygon shapefile provided by the user-UPON FURTHER REFLECTION, THE SPACES BETWEEN THE POLYGONS IN THIS SHAPEFILE COULD BE THE NEGATIVE IMAGE OF RIVERS. While I can look into that, you can use this shapefile as a proxy for data with polygons that have spaces between them but maybe shouldn't.  I'd also be fine with you ignoring that aspect of the shapefile for this step of the mapping.  However, you may need to account for that situation when you are trying to convert data to a scale derived from a user-specified shapefile in terms of how data available in negative space should be handled. 
[@Curtis Atkisson](https://uw-dssg-2024.slack.com/team/U074VQB1HL1)
 let me know if you want to discuss this further)
drinkingwater_use from [ATTAINS_Assessment_20240523.gpkg](https://drive.google.com/file/d/1w5q-ZRx1E817ZTYw_O7SYmujKABx6Y0a/view?usp=drive_link) (values already attached to polygons)
