### ISSUE TITLE
chore: write spec & converter for GeoJSON format

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#155]
The shapefiles outputted by our R script need to be in [GeoJSON](https://geojson.org/) format to be comprehensible as OpenStreetMap layers. We need to specify the different pieces of the GeoJSON object & write a function that converts the current output of `create_index()`, which is a two-column table with index value and geographic ID, to a GeoJSON that associates index values with the relevant geographical units.

**Comment by npovejsil** [comment]
I think this is addressed by #153

**Comment by voglerdaniel** [comment]
Addressed by a feature included in `write_new_polygons` #243
