### ISSUE TITLE
tech-review: understand if toxpiR and webR are compatible

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#158]
WebR requires us to install packages in [a different way](https://docs.r-wasm.org/webr/latest/packages.html) than RStudio. 

A critical dependency of toxpiR has to be installed in an [unconventional way](https://bioconductor.org/packages/release/bioc/html/BiocGenerics.html). `install.packages()` and its WebR equivalent do not work out of the box. 

Is there a workaround that allows us to install `toxpiR` in the web?

**Comment by npovejsil** [comment]
Surely we close this
