### ISSUE TITLE
feat: add data pre-processing diagnostics

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#160]
Fellows brainstormed a few quick tools we can provide to backend creators to confirm that the datasets they are loading follow the prescribed format and will not cause problems when calculating index. A few ideas:

- Generate maps (quick RStudio output, does not have to be pretty) of where a dataset is **missing** values
- Generate visualizations of NANs using [naniar](https://cran.r-project.org/web/packages/naniar/vignettes/getting-started-w-naniar.html)
- Warn users that a high percentage of their overall data is NAN
- Warn users that NAN values have to be imputed to calculate index; may have to be assigned 0 or median

None of these are critical path but may be useful backend tools for creators

**Comment by npovejsil** [comment]
this is pretty much done but I can continue improving it with more printed feedback about data
