### ISSUE TITLE
code: Add countyfips constructor and checker to the function

### ISSUE THREAD

**Issue by Jihyeonbae** [uwescience/WaterReuseDSSG2024#20]
The goal of this task is to check whether county_fips is the identifier, correct it if not, and construct one from constituent parts.

This function will do two things.

1. Check if the county fips identifier is in the format we need (five digits in a character form). The first two digits are state codes. The next three are county codes. 
3. If not, we want to build the county fips identifier that combines state code and county code.  

Input: county_fips | constructor pieces (state id and county id)
Output: character vector with values all of length 5

arguments: cfips=NULL, state=NULL, county=NULL
location: "scripts/utility_functions"

**Comment by atkissoncj** [comment]
Closed by #27 and #51
