### ISSUE TITLE
feat: Enable leaflet remapping functionality 

### ISSUE THREAD

**Issue by Mbye20** [uwescience/WaterReuseDSSG2024#213]

**Comment by npovejsil** [comment]
Let's check if this happens automatically when we re-run the R script. If not, one idea: have a javacript counter that gets input to R. Counts every time the generate button is pressed. If the counter > 0, wipe the leaflet map and remap it.

**Comment by npovejsil** [comment]
Did you guys solve this yesterday by running the remove layer javascript function ?
