### ISSUE TITLE
feat: write generate_button.R 

### ISSUE THREAD

**Issue by npovejsil** [uwescience/WaterReuseDSSG2024#222]
embed WebR capability 
javascript to create generator button that triggers recalculation and remapping

**Comment by npovejsil** [comment]
tiny skeleton made, no javascript yet

**Comment by voglerdaniel** [comment]
We can work together on building this out today if you want - made some progress on the javascript we'd need yesterday. Check out: geo-ndxr/prototype-dev/test_mapping/index_value_v2.html. 

(geo-ndxr/prototype-dev/test_mapping/index_value.html actually integrates this with a choropleth map Mbye created but the HTML is a lot harder to read)

This is also where we will have to build in our call to WebR.

**Comment by npovejsil** [comment]
I'm down - what time are you going to studio?

**Comment by voglerdaniel** [comment]
right after standup
