### ISSUE TITLE
feat: Create skeleton chloropleth mapping on shapefiles 

### ISSUE THREAD

**Issue by npovejsil** [uwescience/WaterReuseDSSG2024#23]

**Comment by voglerdaniel** [comment]
My plan is to implement this as a function with the following form:

`map_cloropleth(dataset, shapefile, join_key.x, join_key.y, variable_of_interest, {style_args})`

This function will:

1. Read in the dataset and shapefile.
2. Verify that join_key.x and join_key.y are the same data type
3. Join the dataset and the shapefile using the designated join keys
4. Map the variable of interest on a chloropleth map; output this map

@atkissoncj Would it be correct to **change this to a feat issue then create a branch referencing this issue?**

**Comment by atkissoncj** [comment]
Yes.

**Comment by voglerdaniel** [comment]
While working on this today, @Jihyeonbae and I encountered a challenge to building a generalizable chloropleth mapping function. **This feature will need to be extensively tested with various shapefiles to ensure that it can handle all of them**. Details below ⬇️ 

---

We were able to create a county-level chloropleth when the `counties` shapefile was generated by `urbnmapr`, but not when the `counties` shapefile was created by `tigris`. 

We could join the data to the shapefiles regardless of which package produced the shapefile. The function broke at the plotting stage. The _counties_ showed up correctly in both cases, suggesting this is not a coordinate system issue. The counties were _correctly colored in_ when the shapefile was from `urbnmapr` but not when it was from `tigris`.

**Comment by atkissoncj** [comment]
Did you look at the structure of objects generated by the different
packages?

**Comment by voglerdaniel** [comment]
At a glance they looked the same, which is why this was surprising. Will investigate in greater detail today

**Comment by atkissoncj** [comment]
Closed with #53
