### ISSUE TITLE
feat: write split_html function as helper to #223

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#232]
In addition to the functions @npovejsil described in issues #217-#223, we need a function that takes an HTML file as input, splits it at a location defined by a regular expression, inserts the HTML generated by the R functions like the ones described in issues #217-#222, and returns the modified HTML.

For example, this is a **rough example** of we'd add a generate button (the HTML in this example probably isn't perfect):
- Take index.html, which contains a map and nothing else
- Run split_html to get two strings: one with everything before "<`div id = "map"`> and one with everything including and after "<`div id = "map"`>". Call these the "before chunk" and the "after chunk"
- Run generate_button to get the HTML & javascript for a generate button
- Append the before chunk, the generate_button HTML + JS, and the after chunk. Return.

**Comment by npovejsil** [comment]
Correct me if I'm wrong but I think #223 addresses this

**Comment by npovejsil** [comment]
or should this issue be a sub/helper function to split HTML and then put that in #223

**Comment by voglerdaniel** [comment]
I was thinking this would be a helper to that function. So the sequence of events in `create_website.R` is something like:
- split_html
- generate_button
- split_html
- download_data
- split_html
- ...

**Comment by npovejsil** [comment]
Oh that's a good idea!!
