### ISSUE TITLE
tech_review: How to get default shape files?

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#26]
Do we need a set of standard shape files that people will use? I would say yes. Minimally
- census tract
- county
- state
- others?

Where do we get these from? Do we download them and just have them in our data folder? Do we do a unique request each time? Do we build in a dependency to a package that has these (and maybe more)?

We also definitely need to allow for a user to specify their own shape files (e.g., watershed/aquifer).

What package or tech should we use for this?

**Comment by Mbye20** [comment]
@atkissoncj We can use the tigris package to get shapefiles of different like states, counties, census tract, regions, congressional district etc

**Comment by Mbye20** [comment]
tigris is a good choice
