### ISSUE TITLE
tech_review: ToxPi and ToxPiR

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#36]
Review and understand how ToxPi works. What are the minimal inputs? What are the maximal inputs? What are the outputs? How will we best use it? Look at [CVI code](https://github.com/wachiuphd/CVI?tab=readme-ov-file)

**Comment by Jihyeonbae** [comment]
(rocket emoji)

**Comment by voglerdaniel** [comment]
ToxPiR has a dependency called BiocGenerics that is not compatible with R 4.4.0. As far as I know, this is the version of R we all have. At this point I'm not able to import ToxPiR, looking for a way to troubleshoot.

**Comment by voglerdaniel** [comment]
Closed by #69
