### ISSUE TITLE
bug: website typo

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#398]
Carolyn says, "Miriam and I would like to share the DSSG website the students put together with folks, but there is a typo. Do you have access to correct the page title in the menu from “iterative” to “interactive.”"

**Comment by atkissoncj** [comment]
anyone have a couple minutes to fix this? Also, might want to get the example on the DSSG website working again. @npovejsil @voglerdaniel ?

**Comment by npovejsil** [comment]
Fixed
