### ISSUE TITLE
feat: User-specified index creation

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#40]
Allow users to specify their own index weightings for individual variables or categories of variables. Allow users to categorize variables.

**Comment by voglerdaniel** [comment]
Whoever picks this up, the [toxpiR docs](https://cran.r-project.org/web/packages/toxpiR/vignettes/introduction.html) are very helpful. The most important thing to understand is slices & how they combine metrics (="allow users to combine variables")
