### ISSUE TITLE
chore: check that chloropleth mapping function correctly maps 4 datasets identified by Carolyn

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#50]
Will be documenting issues with mapping the four datasets here as we test them against the generalized `map_cloropleth()` function part of #23.

1. Flooding risk to roads - county FIPS are 11 digits; FIPS in counties shapefile are 4-5 digits. Need to trim these for mapping to work.
2. WWpctr_5arc.nc - TBA
3. SGD_Coastal_Vulnerabilities.csv - TBA
4. ATTAINS_Assessment -  TBA

**Comment by chayek** [comment]
The flood risk data is at the census tract level, not county. The longer identifier should correspond to a census tract number. Apologies for not clarifying that earlier.

**Comment by voglerdaniel** [comment]
That's very helpful, thank you. I will check if this can be plotted at census tract level
