### ISSUE TITLE
feat: crosswalks data sets on a common scale

### ISSUE THREAD

**Issue by Jihyeonbae** [uwescience/WaterReuseDSSG2024#57]
Write a code that allows different datasets to be transformed into a common scale.

**Comment by chayek** [comment]
check out st_interpolate_aw() https://r-spatial.github.io/sf/reference/interpolate_aw.html 
- the "extensive" input allows you to choose whether the sum is preserved when aggregating (e.g., population count) or whether you keep the mean (e.g., population density)

what it doesn't enable is a weighting factor other than area.  the sf function aggregate() looks like it enables you to feed it a function for aggregating data https://r-spatial.github.io/sf/reference/aggregate.sf.html
