### ISSUE TITLE
project-management: Should we revisit this milestone?

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#6]
This milestone appears in our project schedule, but I think we agreed that the facilitator would be responsible for a specific question list tailored to each interviewee. Should we break this milestone up into multiple, each one corresponding to a specific interviewee and assigned to the facilitator?

**Comment by voglerdaniel** [comment]
Bumping this issue - would we like to break this milestone into several issues, each corresponding to the scheduled stakeholder interview date?

**Comment by voglerdaniel** [comment]
@Miriamhacker

**Comment by atkissoncj** [comment]
@voglerdaniel What do you mean when you refer to "this milestone"?
