### ISSUE TITLE
test: verify that map_choropleth() can handle shapefile-only input

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#61]

**Comment by voglerdaniel** [comment]
@Mbye20 indicated that the function currently does not correctly handle inputs that are shapefiles **only** (not dataset + shapefile that have to be merged) correctly. He will document the issue here. I am creating a new bug fix issue to address this.

**Comment by Mbye20** [comment]
It also does not handle cases when a dataset and a shapefile are already merged.

**Comment by voglerdaniel** [comment]
Would you mind sharing the exact test code that wasn't working for you so that I can ensure the bug fix completely addressed the issue?

**Comment by atkissoncj** [comment]
Was this closed yesterday? Link the PR that closed it
