### ISSUE TITLE
chore: create a list of common scale crosswalks/scales to enable

### ISSUE THREAD

**Issue by chayek** [uwescience/WaterReuseDSSG2024#63]
@Mbye20 @Jihyeonbae 

My datasets currently include the following scale identifiers:

Tigris has:
-Census Tract
-County

-Watershed (HUC -12 or catchment level)
--> looks like you might be able to pull this and other boundaries from the HydroData package!!
https://github.com/mikejohnson51/HydroData
never used it but super excited now!

-Wastewater system identifier (CWNSID)
--> no shapefile currently exists for wastewater service area boundaries.  EPA is currently working on one.  I may try to generate my own basic one using county and congressional district associations, but for now, perhaps we treat this as point data?

-Drinking water system identifier (PWSID)
--> currently using the EPIC shapefile in the GD: https://drive.google.com/drive/folders/1A83sR6ExiyjR2jZFuJcTbC1F5EIzhwtS?usp=drive_link. It is also available online here:  https://www.hydroshare.org/resource/9ebc0a0b43b843b9835830ffffdd971e/
--> I would like to download and use the new EPA version of this dataset (with improved methodology), but I can't seem to figure out how to extract/download it: https://epa.maps.arcgis.com/home/item.html?id=80c6912ef14f46e480f5afd807767b4b
--> EPIC has created a version on hydroshare that incorporates crowd-sourced edits (moderated through Github).  I mention this because I am wondering if putting it in as a dependency downloads a shapefile from online when you call it or if it is a downloaded file stored in the package [I clearly have no idea how this works] Maybe @atkissoncj can weigh in on this.
https://www.hydroshare.org/resource/c9d8a6a6d87d4a39a4f05af8ef7675ad/

**Comment by npovejsil** [comment]
Hi @chayek ! I looked this up but I can't tell if drinking water utility boundaries and wastewater community boundaries are different. I was looking at the EPA website for drinking water boundaries: [(https://www.epa.gov/ground-water-and-drinking-water/community-water-system-service-area-boundaries?tab=resources )]
