### ISSUE TITLE
chore: Review Josh Fortenbaugh interview questions 

### ISSUE THREAD

**Issue by npovejsil** [uwescience/WaterReuseDSSG2024#9]
Interview questions linked [here](https://docs.google.com/document/d/1YUJC3Psy2MU3VH4s4hOgMy3cCFzDFgey/edit#heading=h.3znysh7)

**Comment by atkissoncj** [comment]
@npovejsil Who needs to review these? Can you tag/assign them?

**Comment by miriamhacker** [comment]
See updated questions [here](https://docs.google.com/document/d/1FXcGngfBbiAeIB8D0QWKrFP1Wtmg_5XcUtmDG-HAeDM/edit?usp=sharing)
