### ISSUE TITLE
bug: point mapping

### ISSUE THREAD

**Issue by chayek** [uwescience/WaterReuseDSSG2024#98]
Not sure if this is a bug or I am doing something wrong.  
Using the latest map_utils function. 
Same error regardless of including the shapefile. 

_____ERROR MESSAGE

Coordinate system already present. Adding new coordinate system, which will replace the existing one.
Error in `geom_sf()` at map_points.R:47:4:
! Problem while computing stat.
ℹ Error occurred in the 3rd layer.
Caused by error in `compute_layer()`:
! `stat_sf()` requires the following missing aesthetics: geometry
Run `rlang::last_trace()` to see where the error occurred.

Backtrace:
     ▆
  1. └─global mapper(...)
  2.   └─global map_points(...) at ~/Water-Reuse-DSSG/mapper.R:73:4
  3.     ├─base::print(p) at map_points.R:54:4
  4.     └─ggplot2:::print.ggplot(p)
  5.       ├─ggplot2::ggplot_build(x)
  6.       └─ggplot2:::ggplot_build.ggplot(x)
  7.         └─ggplot2:::by_layer(...)
  8.           ├─rlang::try_fetch(...)
  9.           │ ├─base::tryCatch(...)
 10.           │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 11.           │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 12.           │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 13.           │ └─base::withCallingHandlers(...)
 14.           └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 15.             └─l$compute_statistic(d, layout)
 16.               └─ggplot2 (local) compute_statistic(..., self = self)
 17.                 └─self$stat$compute_layer(data, self$computed_stat_params, layout)
 18.                   └─ggplot2 (local) compute_layer(..., self = self)
 19.                     └─ggproto_parent(Stat, self)$compute_layer(data, params, layout)
 20.                       └─ggplot2 (local) compute_layer(..., self = self)

_____CODE

library(readr)
library(usmap)
library(tidyverse)
library(tigris)
library(sf)

# tell tigris to cache Census shapefile downloads
options(tigris_use_cache = FALSE) 

#Set working directory 
workdir <- "C:/Users/carol/Documents/Water-Reuse-DSSG"
setwd(workdir)

#folder for saving figures and tables
image_folder <- "Analysis/Graphics/"

#only run next line if you haven't created the folder yet
#dir.create(image_folder)

CWNS_path <- "Cleaned at Exisiting Scale/CWNS_merged.csv" 

CWNS <- read.csv(CWNS_path) 

mapper(CWNS, 
       counties() %>% 
         filter(as.numeric(STATEFP) < 60, 
                !(STATEFP %in% c("02", "15"))), 
       location_columns = c("LATITUDE", "LONGITUDE"),
       variable_name = "MGD2022_total", 
       plot_all = TRUE, 
       map_path = image_folder)

**Comment by atkissoncj** [comment]
Can you recreate this bug, @Mbye20 ?

**Comment by npovejsil** [comment]
What is the second argument you put into the function? My guess is it doesn't know how to deal with this: counties() %>%
filter(as.numeric(STATEFP) < 60,
!(STATEFP %in% c("02", "15"))) as an argument.

**Comment by atkissoncj** [comment]
> What is the second argument you put into the function? My guess is it doesn't know how to deal with this: counties() %>% filter(as.numeric(STATEFP) < 60, !(STATEFP %in% c("02", "15"))) as an argument.

@chayek Does this create a shapefile? The second argument of mapper is expected to be a shapefile.

**Comment by Mbye20** [comment]
@chayek I replicated part of what you were doing and I got this map. It is too ugly though. This is the code I used
cwns <- read_csv("private/datasets/cleaned_data/CWNS_merged.csv")

mapper(data = cwns, location_columns = c("LATITUDE", "LONGITUDE"), 
                                         variable_name = "MGD2022_total",
                                         plot = "points", map_path = "private/maps")

![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/78307266/9f10fbfc-fa22-463e-bfc3-1bd814aa1ec2)
