### ISSUE TITLE
feat: Raster mapping in generalized mapping function

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#99]
Can the generalized mapping function do raster data?

**Comment by Mbye20** [comment]
Hey @chayek 
What are you expecting from raster plots? I got this when I plotted the first layer of the wastewater data:
![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/78307266/35407fc7-9b3d-4616-8a12-07b83106c8ab)
Before I used a shapefile to get the value of each county from the raster data which I used to plot this map: 
![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/78307266/de8b6c69-36ce-4bca-b196-463ad3d41ff8)

**Comment by atkissoncj** [comment]
Can you explain why you reopened this, @npovejsil ?
